name: tsh_salesperson_app
description: "TSH Salesperson App - Spider Hand Technical Company (شركة يد العنكبوت التقنية)"
# TSH Unified Architecture System - Mobile Ecosystem v2.0.0
# Author: TSH Technical Team | Date: 2025-06-04
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true

# Shorebird disabled for standard Flutter builds
shorebird:
  enabled: false 